apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "customer-api-integration-polling"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "customer-api-integration-polling"
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: "customer-api-integration-polling"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "customer-api-integration-polling"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: "customer-api-integration-polling"
          command: 
            - /bin/sh
          args:
          - -ec
          - {{ include "integrationService.pollingCommand" . | quote}}
          securityContext:
            {{- toYaml .Values.couchApp.securityContext | nindent 12 }}
          image: "buildpack-deps:curl"
          imagePullPolicy: {{ .Values.couchApp.image.pullPolicy }}
