{{- if .Values.mongodbEnabled }}

{{- if .Values.mongodb.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb.serviceAccountName" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- with .Values.mongodb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
