{{- $rootPasswordValue := (randAlphaNum 32) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "couchdb-creds") }}
{{- if $secret }}
{{- $rootPasswordValue = index $secret.data "password" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: "couchdb-creds"
type: Opaque
data:
  password: {{ $rootPasswordValue}}
  username: {{ "admin" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "docker-hub-creds"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8vdjEvIjp7InVzZXJuYW1lIjoicmd1cHRhNyIsInBhc3N3b3JkIjoiTWl0ZW1hbjQwMDAifX19