{{- if .Values.couchApp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "couchApp.serviceAccountName" . }}
  labels:
    {{- include "couchApp.labels" . | nindent 4 }}
  {{- with .Values.couchApp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
