{{- if .Values.customerApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "customerApi.serviceAccountName" .}}
  labels:
    {{- include "customerApi.labels" . | nindent 4 }}
  {{- with .Values.customerApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
