{{- if .Values.integrationService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "integrationService.serviceAccountName" . }}
  labels:
    {{- include "integrationService.labels" . | nindent 4 }}
  {{- with .Values.integrationService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
